### 데이터 전처리(Preprocessing)

데이터가 상당히 중요하다 머신러닝은. 가비지 데이터가 들어가면 좋은 결과가 나올 수 없다.

* 데이터 클린징 - 잘못되어있는 오류데이터 수정


* 결손값 처리(Null/NaN 처리) - 머신러닝 알고리즘은 결손값을 받아들이지 않으므로 결손값을 어떻게 처리할지 결정 후 수정해줘야함. 아예 없애버린다던가, 평균값을 한다던가.


* 데이터 인코딩(레이블, 원-핫 인코딩) - 머신러닝 알고리즘은 숫자형 값만 받아들임. 기존의 코드성 데이터, 문자열 값으로 들어가서 코드를 표현한다던가 그런걸 다 숫자로 표현해야한다. 그 유형이 레이블, 원-핫 인코딩이 있다.


* 데이터 스케일링 - 정규화, 표준화 등. 가령 신장, 몸무게는 서로 단위가 다르다. cm, kg으로. 이것들을 서로 맞춰서 비교할 수 있는 작업 같은걸 스케일링이라고 한다.


* 이상치 제거 - outlier 같은 택도 없는 값은 제거를 해주는게 좋다. 


* Feature 선택, 추출 및 가공 - 수 많은 피쳐중, 특정 피쳐로만 학습해서 예측을 하는게 더 결과가 좋을 수 있다. 아니면 가공을 해서 또 다른 피쳐로 만든다던가, 가공을 통해서 좀 더 향상된 추출 기법으로 별도의 피쳐들을 만든다던가.

### 데이터 인코딩

머신러닝 알고리즘은 문자열 데이터 속성을 입력 받지 않으며 모든 데이터는 숫자형으로 표현되어야 합니다.


문자형 카테고리형 속성은 모두 숫자값으로 변환/인코딩 되어야 합니다.

* 레이블 인코딩(Label encoding)

이건 쉽다. 코드형 숫자값으로 바꾸는 것임

In [2]:
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# LabelEncoder를 객체로 생성한 후 , fit( ) 과 transform( ) 으로 label 인코딩 수행. 
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:',labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [3]:
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [4]:
print('디코딩 원본 값:',encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))

디코딩 원본 값: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


* 원-핫 인코딩(One-Hot encoding)

레이블 인코딩은 의 문제: 의도하지 않게 숫자간의 크기 차이가 발생함. 결국 관계성이 생겨버림.(2가 1보다 큰 것처럼.) 그래서 나온게 원-핫 인코딩

* 사이킷런 - 원-핫 인코딩

사이킷런의 원핫인코딩은 약간 번잡하다.
왜냐? 먼저 숫자값으로 변환을 스스로 못한다.
그래서 레이블인코더로 숫자값으로 먼저 변환을 해야함.

원본 데이터 → 숫자로 인코딩 → 원-핫 인코딩

In [5]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환합니다. 
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 2차원 데이터로 변환합니다. 
labels = labels.reshape(-1,1) #컬럼은 무조건하나, 행은 동적으로 할당

# 원-핫 인코딩을 적용합니다. 
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


~~~
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(
    transformers=[
        ("Country",        # Just a name
         OneHotEncoder(), # The transformer class
         [0]            # The column(s) to be applied on.
         )
    ], remainder='passthrough'
)
X = transformer.fit_transform(X)
Reminder will keep previous data while [0]th column will replace will be encoded
~~~
사이킷런 0.22 버전부터 이런식으로 코드를 작성할 수 있다.
LabelEncoder를 더 이상 사용할 필요가 없다.

In [1]:
import sklearn
print(format(sklearn.__version__))

0.23.2


In [15]:
# LabelEncorder를 쓰지 않고 시도

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']
labels = encoder.transform(items)
print('transform만 했을때:', labels)

labels = labels.reshape(-1,1) #컬럼은 무조건 하나, 행은 동적으로 할당(2차원으로)

print('reshape(-1,1)을 했을 때:', labels)


transformer = ColumnTransformer(
    transformers=[
        ("items",        # Just a name
         OneHotEncoder(), # The transformer class
         [0]            # The column(s) to be applied on.
         )
    ], remainder='passthrough'
)
labels = transformer.fit_transform(labels)

# Reminder will keep previous data while [0]th column will replace will be encoded

transform만 했을때: [0 1 4 5 3 3 2 2]
reshape(-1,1)을 했을 때: [[0]
 [1]
 [4]
 [5]
 [3]
 [3]
 [2]
 [2]]


In [16]:
print(labels)
print(labels.toarray())
print(labels.shape)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 4)	1.0
  (3, 5)	1.0
  (4, 3)	1.0
  (5, 3)	1.0
  (6, 2)	1.0
  (7, 2)	1.0
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)


2020/09/08 LabelEncoder() 문제
0.21 버전에서만 오류가 났었음. 


sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
  
오류 발생.

참고: 스택오버플로우

https://stackoverflow.com/questions/54345667/onehotencoder-categorical-features-depreciated-how-to-transform-specific-column

#### 더 편하게 할 수 있는 방법이 있다. 

### 판다스 get_dummies( ) 를 이용한 원-핫 인코딩

In [19]:
import pandas as pd

df = pd.DataFrame({'item':['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서'] })
df

item
0    TV
1   냉장고
2  전자렌지
3   컴퓨터
4   선풍기
5   선풍기
6    믹서
7    믹서

In [20]:
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0        1         0        0         0          0         0
1        0         1        0         0          0         0
2        0         0        0         0          1         0
3        0         0        0         0          0         1
4        0         0        0         1          0         0
5        0         0        0         1          0         0
6        0         0        1         0          0         0
7        0         0        1         0          0         0

In [21]:
item_dummies = pd.get_dummies(df)
print(item_dummies)

   item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0        1         0        0         0          0         0
1        0         1        0         0          0         0
2        0         0        0         0          1         0
3        0         0        0         0          0         1
4        0         0        0         1          0         0
5        0         0        0         1          0         0
6        0         0        1         0          0         0
7        0         0        1         0          0         0


원핫으로 변경은 됐는데 이걸 어떻게 사용하지? 나중에 실습하려나

### 피처 스케일링과 정규화

* 표준화: 데이터의 피처 각각이 평균이 0이고 분산이 1인 가우시안 정규분포를 가진 값으로 변환하는 것을 의미


* 정규화는 서로 다른 피처의 크기를 통일하기 위해 크기를 변환해주는 개념  
예: 차가 갈 수 있는 거리 km 연봉: 원, 달러, 엔
이걸 0에서 1까지 정규화 시켜주세요~

* StandardScaler: 평균이 0이고, 분산이 1인 정규 분포 형태로 변환

In [22]:
from sklearn.datasets import load_iris
import pandas as pd
# 붓꽃 데이터 셋을 로딩하고 DataFrame으로 변환합니다. 
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature 들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())


feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


결과: 평균은 0이 아니고 분산은 1이 아니다

In [23]:
from sklearn.preprocessing import StandardScaler

# StandardScaler객체 생성
scaler = StandardScaler()
# StandardScaler 로 데이터 셋 변환. fit( ) 과 transform( ) 호출.  
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

#transform( )시 scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature 들의 분산 값')
print(iris_df_scaled.var())

feature 들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


결과: 평균 값은 거의 0이다. 분산 값은 거의 1이다.

* MinMaxScaler: 데이터값을 0과 1사이의 범위 값으로 변환(음수 값이 있으면 -1에서 1값으로 변환)

In [24]:
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler객체 생성
scaler = MinMaxScaler()
# MinMaxScaler 로 데이터 셋 변환. fit() 과 transform() 호출.  
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform()시 scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 최소 값')
print(iris_df_scaled.min())
print('\nfeature들의 최대 값')
print(iris_df_scaled.max())


feature들의 최소 값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최대 값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
