## 8.2 텍스트 사전 준비 작업(텍스트 전처리) - 텍스트 정규화

NLTK 패키지를 이용해서 수행 해볼 것임.

굉장히 유명한 패키지. NLP 패키지의 시조새 같은, 굉장히 많은 내용을 담고 있고 아카데믹하게 학자들이 고민한 내용들이 많이 들어가 있음.

그 안에 들어가있는 굉장히 유용한 말뭉치 사전들, 그런것들이 굉장히 많다. 기반으로 다양한 NLP 테스트를 해볼 수 있는 것을 제공해줌.

지금은 NLTK가 딥러닝이나 이런 모델들과는 시대적으로 뒤쳐져서 많이 사용하진 않지만 딥러닝 기반이 나오기전까지만 하더라도

NLTK는 기본적으로 생각하고 가는 패키지였었다. 

이걸 직접 쓰는 경우는 거의 없을 것임. 굳이 이걸 소개하는 이유는 개념상으로 조금 쉽게 이해하기 위해서 이런 패키지로 이러이러한 것들을

수행한다라는걸 보기 위해서임. 직접 이 코드를 쓸 일은 없을 것이다.

### Text Tokenization

**문장 토큰화**

In [1]:
#import nltk
#nltk.download('punkt')

In [2]:
from nltk import sent_tokenize
text_sample = 'The Matrix is everywhere its all around us, here even in this room.  \
              You can see it out your window or on your television. \
               You feel it when you go to work, or go to church or pay your taxes.'
sentences = sent_tokenize(text=text_sample)
print(type(sentences),len(sentences))
print(sentences)

<class 'list'> 3
['The Matrix is everywhere its all around us, here even in this room.', 'You can see it out your window or on your television.', 'You feel it when you go to work, or go to church or pay your taxes.']


위 결과를 보면, 마침표 기준으로 3개가 나뉘었다. \ 없이도 3개로 나뉜다. \를 한 이유는 인터프리터 기준으로 파이썬이 인지하게 하려고 했을 뿐 의미없음.

**단어 토큰화**

문장이 하나 주어졌으면 공백으로 보통 토크나이즈를 한다.

In [3]:
from nltk import word_tokenize

sentence = "The Matrix is everywhere its all around us, here even in this room."
words = word_tokenize(sentence)
print(type(words), len(words))
print(words)

<class 'list'> 15
['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.']


**여러 문장들에 대한 단어 토큰화**

In [4]:
from nltk import word_tokenize, sent_tokenize

#여러개의 문장으로 된 입력 데이터를 문장별로 단어 토큰화 만드는 함수 생성
def tokenize_text(text):
    
    # 문장별로 분리 토큰
    sentences = sent_tokenize(text)
    # 분리된 문장별 단어 토큰화
    word_tokens = [word_tokenize(sentence) for sentence in sentences]
    return word_tokens

#여러 문장들에 대해 문장별 단어 토큰화 수행. 
word_tokens = tokenize_text(text_sample)
print(type(word_tokens),len(word_tokens))
print(word_tokens)

<class 'list'> 3
[['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.'], ['You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.'], ['You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes', '.']]


**n-gram**

In [5]:
from nltk import ngrams

sentence = "The Matrix is everywhere its all around us, here even in this room."
words = word_tokenize(sentence)

all_ngrams = ngrams(words, 2)
ngrams = [ngram for ngram in all_ngrams]
print(ngrams)

[('The', 'Matrix'), ('Matrix', 'is'), ('is', 'everywhere'), ('everywhere', 'its'), ('its', 'all'), ('all', 'around'), ('around', 'us'), ('us', ','), (',', 'here'), ('here', 'even'), ('even', 'in'), ('in', 'this'), ('this', 'room'), ('room', '.')]


### Stopwords 제거

Stopwords는 분석적으로 큰 의미가 없다.

In [8]:
import nltk
#nltk.download('stopwords')

NLTK 는 패키지가 워낙 커서 필요한걸 받아가면서 해야한다.

corpus(말뭉치)라는 패키지는 굉장히 많은 연구용 말뭉치를 가지고 있다. 

그 중에 필요한 stopwords의 words 중 neglish의 스탑워즈 갯수를 확인해보자.

In [9]:
print('영어 stop words 갯수:',len(nltk.corpus.stopwords.words('english')))
print(nltk.corpus.stopwords.words('english')[:40])

영어 stop words 갯수: 179
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this']


In [10]:
import nltk

stopwords = nltk.corpus.stopwords.words('english')
all_tokens = []
# 위 예제의 3개의 문장별로 얻은 word_tokens list 에 대해 stop word 제거 Loop
for sentence in word_tokens:
    filtered_words=[]
    # 개별 문장별로 tokenize된 sentence list에 대해 stop word 제거 Loop
    for word in sentence:
        #소문자로 모두 변환합니다. 
        word = word.lower()
        # tokenize 된 개별 word가 stop words 들의 단어에 포함되지 않으면 word_tokens에 추가
        if word not in stopwords:
            filtered_words.append(word)
    all_tokens.append(filtered_words)
    
print(all_tokens)

[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['see', 'window', 'television', '.'], ['feel', 'go', 'work', ',', 'go', 'church', 'pay', 'taxes', '.']]


이렇게 코드를 직접 쓸 일은 없을 것임. NLP 패키지에 파라미터만 넣어두면 됨.

### Stemming과 Lemmatization

In [11]:
from nltk.stem import LancasterStemmer
stemmer = LancasterStemmer()

print(stemmer.stem('working'),stemmer.stem('works'),stemmer.stem('worked'))
print(stemmer.stem('amusing'),stemmer.stem('amuses'),stemmer.stem('amused'))
print(stemmer.stem('happier'),stemmer.stem('happiest'))
print(stemmer.stem('fancier'),stemmer.stem('fanciest'))

work work work
amus amus amus
happy happiest
fant fanciest


In [15]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\esaw2\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.


True

In [16]:
from nltk.stem import WordNetLemmatizer

lemma = WordNetLemmatizer()
print(lemma.lemmatize('amusing','v'),lemma.lemmatize('amuses','v'),lemma.lemmatize('amused','v'))
print(lemma.lemmatize('happier','a'),lemma.lemmatize('happiest','a'))
print(lemma.lemmatize('fancier','a'),lemma.lemmatize('fanciest','a'))

amuse amuse amuse
happy happy
fancy fancy


<h1>텍스트의 피처 벡터화 유형</h1>

- Bag of Words : BOW는 예를 들어서 100개의 문서가 있다면 모든 문서의 단어를 다 추출해서 피쳐로 만듦. 그 다음에 다큐멘터들이 이런 피쳐들을 값으로 가짐. 개별 단어들이 이런 피쳐에 대해서 값을 어떻게 설정하냐면 이 단어가 나타난 횟수가 몇번이냐. doc1은 단어1이 3번 나왔고 2는 4번. 이렇게 횟수를 표현 Document Term Matrix : Term은 단어를 말함.


- Word Embedding: Word Embedding은 똑같이 100개의 문서가 있따면 N개의 차원을 만듦. D1, D2, D3, D4, D5 이런식으로 만들어진 차원축에 기반해서 개별 단어들을 벡터 축으로 가져갈 수 있음. 4개의 단어만 있다고 가정을 해보면, X,Y 두개의 축, 직관적으로 봐도 Queen과 WOMNAN, KING과 MAN의 관계를 보면 x 값이 같으므로 유사하다고 볼 수 있음. 

<img src="./img/TextVectorization1.png"/>

<h1>Bag of Words - BOW</h1><br>



<img src="./img/BOW1.png"/>

<h2>Bag-of-Words 구조</h2><br>

개별 단어를 bag에다 다 넣고 섞고 중복을 제거한다. 그리고 각 단어에 고유 인덱스 위치 값을 다 부여한다. 그리고 개별 단어에 대해서 각 문장들이 예를 들어서 Counter Vectorization을 한다고하면 and는 문장1에서 한번, baseball에서 2번 등 이런식으로.

헷갈릴 수 잇는 것: 어떨때는 왜 문장이고 어떨때는 문서인가? 그건 업무마다 다르다. 

<img src="./img/Bag_of_Words1.png"/>

<h2>BOW 장단점</h2><br>
 

- 장점: Word Embedding보다 빠르다.굳이 '예상보다' 문서의 특징을 잘 타나낸다고 쓴 이유는, 아직도 쓸만하기 때문. Word2vec을 쓰나 BOW를 쓰나 말이 많은데 경험적으로 말하자면 현재 기준에선 BOW가 그렇게까지 떨어지 않는다. 오히려 비슷하거나 더 높을때도 많다.

- 단점으론 희소 행렬 문제가 있는데 피쳐가 몇만개씩 나오고 그런다면 하나에 문서에 몇만개의 단어를 다 쓰진 않다. 5만개중 5천개라고 했을때 10%만 데이터가 차고 나머지는 다 안찰 것이다. 이걸 Null로 둘 수 없으니까 0으로 채우면 메모리 문제가 생기도 하고 그렇다.
 
<img src="./img/BOW2.png"/>

<h1>BOW 피쳐 벡터화(Feature Vectorization)</h1><br>

이렇게 Doc이 M개가 있으면 M x N개의 피처가 벡터화 된다

<img src="./img/Feature_Vectorization1.png"/>

<h2>BOW 피처 벡터화 유형</h2><br>


단순 카운트 기반의 벡터화의 문제: 가령 문서 1에서 어떤 단어가 횟수가 많이 나왔다. 20번 정도. 그럼 중요한 단어로 인식할 수 있다. 그러나 글을 쓸때 생각해보면 딱히 그렇지 않다. 예를 들어 증권이라고 해보자. 거기서 자주 나오는 단어를 봤더니 주가 싯가 종가 등 기본적인 증권 업무의 단어가 많이 나온다고 보자. 이걸 중요한 단어로 파악해서 정보량을 많이 주게 되면 정확한 머신러닝 알고리즘이 돌 수 잇는 중요한 피쳐 역할을 못해준다. 가령 증권영역에 다양한 서브 영역별로 카테고리를 나누고 싶어도 나놀 수 가 없다.

보통 문서의 크기가 크고 문서가 굉장히 많을때는 TF-IDF를 적용함. 여기서는 카운트 기반의 벡터 문제같은 단어를 페널티를 준다. 많은 문서에서 똑같이 반복되서 나오면 NOK(not ok)

<img src="./img/BOWFeatureVectorization1.png"/>

<h2>TF-IDF(Term Frequency Inverse Document Frequency)</h2><br>

특정 단어가 다른 문서에 없고 특정 문서에만 자주 사용 된다면 중요단어.

예를 들어 증권이라면, '서킷 브레이크' 라던가. 

IDF는 DF의 역수이다. 근데 그냥 역수가 아니라 전체문서수/DF 즉 N/DF

TF는 높을수록 좋은게 맞다. 그런데 TF도 놓지만 DF도 높다면 분모가 커지니까 값이 작아지게 된다. 

가령 예를 들어서 DF가 4인데 전체문서가 4 나오면 log 4/4 = log 1=  0 이 되어버린다.



<img src="./img/BOWFeatureVectorization2.png"/>

<h1>사이킷런 CounterVectorizer 초기화 파라미터</h1><br>

- max_df: 문서가 3개 있다고 해보자. 특정단어가 문서1=30 문서2=50 문서3=21 번 나왔다고 하자. max_df=100으로 정수값을 주게 되면, 특정 단어가 101번 전체 문서에 걸쳐서 나오면 이 피쳐는 삭제(즉 필터링)되는거임. 만약 소수점으로 주게 되면 max_df=0.95라면 전체의 95%까지만 던아로 추출하고 상위 5%는 추출하지 않는다. 너무 자주 반복되는 단어들을 필터링하고 싶을때는 max_df를 쓴다.

- min_df: 이거는 거의 안나오는 단어를 필터링. 너무 낮으면 garbage 성이다

- max_features: 이거는 아예 숫자를 지정하는 것. 

- stop_words: 스톱 워드로 지정된 것 필터링.

- ngram_range: n-gram 형태로 파싱하기 위한건데 살짝 다르다. range 때문에 다름. 디폴트는 (1,1)이다. (1,2)로 하면 이게 바로 레인지이다. 1도 포함을 하고 2도 포함하라는거임.. 앞에 배웠던 바이그램만 시키려면 (2,2)를 해야한다.

- analyzer

- token_patter

- lower_case

<img src="./img/CounterVectorizer1.png"/>

<img src="./img/CounterVectorizer2.png"/>

### 8.3 Bag of Words – BOW

**사이킷런 CountVectorizer 테스트**

두개의 문장을 만들 것임. 그것을 리스트로 하나로 합쳤다.

In [20]:
text_sample_01 = 'The Matrix is everywhere its all around us, here even in this room. \
                  You can see it out your window or on your television. \
                  You feel it when you go to work, or go to church or pay your taxes.'
text_sample_02 = 'You take the blue pill and the story ends.  You wake in your bed and you believe whatever you want to believe\
                  You take the red pill and you stay in Wonderland and I show you how deep the rabbit-hole goes.'
text=[]
text.append(text_sample_01); text.append(text_sample_02)
print(text,"\n", len(text))

['The Matrix is everywhere its all around us, here even in this room.                   You can see it out your window or on your television.                   You feel it when you go to work, or go to church or pay your taxes.', 'You take the blue pill and the story ends.  You wake in your bed and you believe whatever you want to believe                  You take the red pill and you stay in Wonderland and I show you how deep the rabbit-hole goes.'] 
 2


**CountVectorizer객체 생성 후 fit(), transform()으로 텍스트에 대한 feature vectorization 수행**

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

# Count Vectorization으로 feature extraction 변환 수행. 
cnt_vect = CountVectorizer()
cnt_vect.fit(text)

CountVectorizer()

In [22]:
ftr_vect = cnt_vect.transform(text)

**피처 벡터화 후 데이터 유형 및 여러 속성 확인**

In [23]:
print(type(ftr_vect), ftr_vect.shape)
print(ftr_vect)

<class 'scipy.sparse.csr.csr_matrix'> (2, 51)
  (0, 0)	1
  (0, 2)	1
  (0, 6)	1
  (0, 7)	1
  (0, 10)	1
  (0, 11)	1
  (0, 12)	1
  (0, 13)	2
  (0, 15)	1
  (0, 18)	1
  (0, 19)	1
  (0, 20)	2
  (0, 21)	1
  (0, 22)	1
  (0, 23)	1
  (0, 24)	3
  (0, 25)	1
  (0, 26)	1
  (0, 30)	1
  (0, 31)	1
  (0, 36)	1
  (0, 37)	1
  (0, 38)	1
  (0, 39)	1
  (0, 40)	2
  :	:
  (1, 1)	4
  (1, 3)	1
  (1, 4)	2
  (1, 5)	1
  (1, 8)	1
  (1, 9)	1
  (1, 14)	1
  (1, 16)	1
  (1, 17)	1
  (1, 18)	2
  (1, 27)	2
  (1, 28)	1
  (1, 29)	1
  (1, 32)	1
  (1, 33)	1
  (1, 34)	1
  (1, 35)	2
  (1, 38)	4
  (1, 40)	1
  (1, 42)	1
  (1, 43)	1
  (1, 44)	1
  (1, 47)	1
  (1, 49)	7
  (1, 50)	1


위 결과를 보면 type이 csr_matrix이다. 희소행렬을 물리적으로 공간을 절약하고 개선을 빨리하기 위한 유형임.

값을 까보니까 뭔가 모르는 (0, 0) ~ 등이 있는데 이게 바로 각각 단어들의 위치를 말해주는 것임. 그 오른쪽의 숫자 1은 다큐먼트 1의 1번째 것이 1번 나왔다는 것임.

**행 값이 어떤게 나왔는지 알려면 .vocabulary_**

이 속성을 확인하면 index가 나온다. the 는 38번 index, matrix는 22번째 index 라는 뜻.

위에 찾아보면 (0,22) 1 인데 matrix가 첫번째 문서에 1번 나왔다는 뜻임.

(1, 22) 가 없으므로 두번째 문서에서는 안나왔다는 뜻임.

In [24]:
print(cnt_vect.vocabulary_)

{'the': 38, 'matrix': 22, 'is': 19, 'everywhere': 11, 'its': 21, 'all': 0, 'around': 2, 'us': 41, 'here': 15, 'even': 10, 'in': 18, 'this': 39, 'room': 30, 'you': 49, 'can': 6, 'see': 31, 'it': 20, 'out': 25, 'your': 50, 'window': 46, 'or': 24, 'on': 23, 'television': 37, 'feel': 12, 'when': 45, 'go': 13, 'to': 40, 'work': 48, 'church': 7, 'pay': 26, 'taxes': 36, 'take': 35, 'blue': 5, 'pill': 27, 'and': 1, 'story': 34, 'ends': 9, 'wake': 42, 'bed': 3, 'believe': 4, 'whatever': 44, 'want': 43, 'red': 29, 'stay': 33, 'wonderland': 47, 'show': 32, 'how': 17, 'deep': 8, 'rabbit': 28, 'hole': 16, 'goes': 14}


In [27]:
# cnt_vect = CountVectorizer(max_features=5) # stop_words를 안했더니 의미없는 the, you, your 등이 나옴
cnt_vect = CountVectorizer(max_features=5, stop_words='english')
cnt_vect.fit(text)
ftr_vect = cnt_vect.transform(text)
print(type(ftr_vect), ftr_vect.shape)
print(cnt_vect.vocabulary_)


<class 'scipy.sparse.csr.csr_matrix'> (2, 5)
{'window': 4, 'pill': 1, 'wake': 2, 'believe': 0, 'want': 3}


**ngram_range 확인**

In [33]:
cnt_vect = CountVectorizer(ngram_range=(1,3)) # 1도하고 2도하고 3도 하라는 것임. 1 + 2 + 3
# cnt_vect = CountVectorizer(ngram_range=(1,2)) # 디폴트로 1도 하고 2도 하라는 얘기임. 1 + 2 를 하는 것이다. the matrix부터 바이그램하기 시작했다.
cnt_vect.fit(text)
ftr_vect = cnt_vect.transform(text)
print(type(ftr_vect), ftr_vect.shape)
print(cnt_vect.vocabulary_)

<class 'scipy.sparse.csr.csr_matrix'> (2, 201)
{'the': 129, 'matrix': 77, 'is': 66, 'everywhere': 40, 'its': 74, 'all': 0, 'around': 11, 'us': 150, 'here': 51, 'even': 37, 'in': 59, 'this': 140, 'room': 106, 'you': 174, 'can': 25, 'see': 109, 'it': 69, 'out': 90, 'your': 193, 'window': 165, 'or': 83, 'on': 80, 'television': 126, 'feel': 43, 'when': 162, 'go': 46, 'to': 143, 'work': 171, 'church': 28, 'pay': 93, 'taxes': 125, 'the matrix': 132, 'matrix is': 78, 'is everywhere': 67, 'everywhere its': 41, 'its all': 75, 'all around': 1, 'around us': 12, 'us here': 151, 'here even': 52, 'even in': 38, 'in this': 60, 'this room': 141, 'room you': 107, 'you can': 177, 'can see': 26, 'see it': 110, 'it out': 70, 'out your': 91, 'your window': 199, 'window or': 166, 'or on': 86, 'on your': 81, 'your television': 197, 'television you': 127, 'you feel': 179, 'feel it': 44, 'it when': 72, 'when you': 163, 'you go': 181, 'go to': 47, 'to work': 148, 'work or': 172, 'or go': 84, 'to church': 146, '

<h1>희소행렬의 이해</h1><br>
<h2>CounterVectorizer를 이용한 피처 벡터화</h2><br>

벡터화했더니 익숙하지 않은 CSR_matrix같은게 나온는데 이게 휘소행렬이다.

수천 수만개 문서가 있다면 모든 단어를 다 나열하기 떄문에 굉장히 많은 단어들이 나온다.

개별문서가 그 단어를 가지고 있을 확률이 일부만 가지고 있을거다. 사전도 아니고.

그렇기 떄문에 BOW피쳐 벡터화 모델은 너무 많은 0값이 메모리에 할당이되기 때문에 많은 메모리 공간도 필요하고 연산 속도에도 영향을 미친다.

그러므로 희소행렬을 변환을 하는데 COO형식과 CSR형식이 있다. 0이 아닌 값만 저장하고 그 값들의 위치만 기억하면 된다.

<img src="./img/CounterVectorizer3.png"/>

<h1>희소행렬</h1><br>

<img src="./img/COOCSR1.png"/>

<h2>희소행렬의 저장 변환 공식</h2><br>

COO, CSR 형식

굳이 다 이해할 필요는 없고 이런게 있다하고 상식선에서만 생각하면 된다.

<img src="./img/COOCSR2.png"/>

<h2>COO 형식</h2><br>

COO 형식은  0이 아닌 데이터 값만 추출해서 그 행과 열 위치를 추출하여 그 인덱스를 기억하는 것

<img src="./img/COO1.png"/>

<h2>CSR 형식</h2><br>

COO형식의 문제인, 행 위치 배열의 중복값들도 커질 수 있으므로 행 위치배열을 어떻게 바꾸냐면 행위치 배열의 위치 배열 인덱스(위치의 위치. 인덱스의 인덱스)

총 항목 개수 배열을 가지면 그게 13이면 12가 마지막임을 알 수 있다. 훨씬 더 간단하게 메모리를 줄일 수 있다.

<img src="./img/CSR1.png"/>

### 희소 행렬 - COO 형식

원본 행렬이 아래와 같이 있다고 하자.

In [34]:
import numpy as np

dense = np.array( [ [ 3, 0, 1 ], 
                    [0, 2, 0 ] ] )

In [35]:
from scipy import sparse

# 0 이 아닌 데이터 추출
data = np.array([3,1,2])

# 행 위치와 열 위치를 각각 array로 생성 
row_pos = np.array([0,0,1])
col_pos = np.array([0,2,1])

# sparse 패키지의 coo_matrix를 이용하여 COO 형식으로 희소 행렬 생성
sparse_coo = sparse.coo_matrix((data, (row_pos,col_pos)))

In [36]:
print(type(sparse_coo))
print(sparse_coo)
dense01=sparse_coo.toarray() # 다시 원본 행렬로 반환하려면 toarray()를 하면 된다.
print(type(dense01),"\n", dense01)

<class 'scipy.sparse.coo.coo_matrix'>
  (0, 0)	3
  (0, 2)	1
  (1, 1)	2
<class 'numpy.ndarray'> 
 [[3 0 1]
 [0 2 0]]


### 희소 행렬 – CSR 형식

이것도 유사하다.

In [37]:
from scipy import sparse

dense2 = np.array([[0,0,1,0,0,5],
             [1,4,0,3,2,5],
             [0,6,0,3,0,0],
             [2,0,0,0,0,0],
             [0,0,0,7,0,8],
             [1,0,0,0,0,0]])

# 0 이 아닌 데이터 추출
data2 = np.array([1, 5, 1, 4, 3, 2, 5, 6, 3, 2, 7, 8, 1])

# 행 위치와 열 위치를 각각 array로 생성 
row_pos = np.array([0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 4, 4, 5])
col_pos = np.array([2, 5, 0, 1, 3, 4, 5, 1, 3, 0, 3, 5, 0])

# COO 형식으로 변환 
sparse_coo = sparse.coo_matrix((data2, (row_pos,col_pos)))

# 행 위치 배열의 고유한 값들의 시작 위치 인덱스를 배열로 생성
row_pos_ind = np.array([0, 2, 7, 9, 10, 12, 13])

# CSR 형식으로 변환 
sparse_csr = sparse.csr_matrix((data2, col_pos, row_pos_ind))

print('COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_coo.toarray())
print('CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_csr.toarray())


COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


In [38]:
print(sparse_csr)

  (0, 2)	1
  (0, 5)	5
  (1, 0)	1
  (1, 1)	4
  (1, 3)	3
  (1, 4)	2
  (1, 5)	5
  (2, 1)	6
  (2, 3)	3
  (3, 0)	2
  (4, 3)	7
  (4, 5)	8
  (5, 0)	1


**그냥 간단하게 아래와 같이도 가능하다.**

In [39]:
dense3 = np.array([[0,0,1,0,0,5],
             [1,4,0,3,2,5],
             [0,6,0,3,0,0],
             [2,0,0,0,0,0],
             [0,0,0,7,0,8],
             [1,0,0,0,0,0]])

coo = sparse.coo_matrix(dense3)
csr = sparse.csr_matrix(dense3)