<h2>잠재 요인 협업 필터링의 개요</h2>

잠재 요인 협업 필터링은 행렬분해기법을 이용한다.

그래서 6장에서 행렬분해에 대해서 집중해서 말했었다.

가물가물하면 이거 시작하기전에 6장에 SVD쪽을 다시 한번 공부하고 리프레시하는거 추천.

사용자 아이템 평점 행렬은 희소행렬이다. 이 희소행렬을 다시 행렬분해를 통해서 분해를 하는데,

이 분해가 됐을때는 잠재요인이라는 사용자와 잠재요인간, 잠재요인과 아이템간 즉 두개의 댄스.

밀집된 행렬로 분해가 된다. 이렇게 분해된 댄스행렬들을 재결합을해서 잡음이 제거된 그런 형태가 되는거다.

R'는 댄스형태로 제구성된 예측 평점 데이터 셋,

R은 사용자가 선택하지 않음 아이템에 대한 평점을 재구성하면서 잠재요인이라는 특성을 추출하면서

평점을 잠재요인 기반으로 (4라던가 3이라던가) 예측이 가능한 그런걸로 만들 수 있다.

<img src="./img/latentFactor1.png">

<h2>잠재 요인 협업 필터링의 이해</h2>

잠재요인 협업필터링의 잠재요인이 뭐라고 특징짓기는 사실은 어렵다. 

가령 예를 들어서, 이 영화의 잠재 요인인데 이걸 '장르'라고 가정해보자.

그렇게해서 사용자 레벨의 잠재요인, 아이템 레벨의 잠재요인 두개의 밀집행렬로 분해가 된다고 말했었다.

그것들을 살펴보면 사용자 레벨의 잠재요인을보면 SF에 대해 0.7의 선호도를 가지고 있고

Horror에는 0.6 정도 등.. 마찬가지로 아이템에서 보면 영화로 예를 들었을때 프로메테우스는 SF는 0.8, horror는 0.6 등 영화 하나가 여러가지 장르로 구성되어있는데 어떤 잠재요인으로 구성되어있는지를 

두개의 댄스행렬로 분해가 되는거다.

<img src="./img/latentFactorComprehension.png">

<h2>잠재 요인 협업 필터링 - 넷플릭스 추천 엔진 경연</h2>

넷플릭스 추천 엔진 경연 대회에서 이게 많이 두각을 냈고, 

우승팀 뿐만 아니라 상위팀 대부분이 잠재 요인 협업 필터링을 사용을 했다.

<img src="./img/latentFactorNetflix.png">

<h2>행렬 분해를 통한 잠재 요인 협업 필터링</h2>

원본 사용자-아이템 평점 행렬(parse한, 희소행렬)이 P 와 Q^t로

댄스(dense)로 바뀌어지는거다. 그러면서 이 두개의 분해된 행렬들이 다시 재결합을 해서,

이제는 예측이 되는. 밀집 행렬 형태의 사용자-아이템 평점 행렬을 생성한다.

예전에는 평점을 메기지 않은 데이터에 대해서 평점을 예측할 수 있는 것이다.

<img src="./img/DecompositionMatrixlatentFactor.png">

<h2>행렬 분해를 통한 잠재 요인 협업 필터링</h2>

이제 말했던 것을 예를 한번 들어보겠다.

원본 행렬을 보면 희소행렬로 되어있다. 빈 칸을 알고 싶으면 분해를 한다. 

사용자-잠재 요인, 잠재요인 행렬로 분해를 한다.

user1은 factor1, factor2를 가지고 있다.

factor1의 item 요소들은 1.7, 2.3 등으로 되어 있다.

item1의 기준으로 보면 factor1에서 1.7, factor2에서 2.49를 가지고 있다.

이걸 내적을 해서 재결합을 하게 된다.

사용자 평점 행렬은 이제 잠재요인이라는걸 감안을 하는거다. 어떤 사용자가 어떤 잠재요인이라는걸 가지고 있으면,

내적을 해서 예측 평점이 나오게 되는 것 이다.

이렇게 해서 평가가 안된 항목에 대해 예측을 할 수 있다.

<img src="./img/DecompositionMatrixlatentFactor1.png">

<h2>행렬 분해를 통한 잠재 요인 협업 필터링</h2>

위에 말했던걸 다시 설명해보겠다.

R[1,1]을 위치인덱스라 생각하지말고 사용자 유저아이디가 1이고 item이 1 이라고 생각하자. 

그래서 user1의 사용자별 장르 선호도가 0.94, 0.96으로 나왔다는 것임.

그림 잘보면 이해할 수 있다.

<img src="./img/DecompositionMatrixlatentFactor2.png">

R[ 1, 2 ] 의 경우도 한번 보자. 내적곱을 해서 예측 값을 구하는거다.

<img src="./img/DecompositionMatrixlatentFactor3.png">

<h2>잠재 요인 기반의 행렬 분해 이해</h2>

이제 일반론을 시켜보자. SVD를 하면 이걸 이해해야한다 U 시그마 V Transpose의 행렬 분해도 

R = P * Q Transpose(P내적 Q 트랜스포즈)

원본 행렬의 사용자가 M개를 가지고 있고 아이템은 N개로 구성된 M x N 를 가진 행렬의 구성이다. 

그러면 이 행렬은 어떻게 분해될 수 잇냐면 K개 유저는 M 즉 M x K 를 가진 P 행렬과 

잠재요인 K * 아이템 N 으로 구성될 수 있다.

SVD도 마찬가지, M*N이 원본 행렬이면 길쭉이(M * K)와 넙죽이(K * N)로 분해 될 수 있다.

Q가 헷갈릴 수 있는데 Q는 아이템과 잠재 요인이다. 

<img src="./img/LatentFactorCom1.png">

<h2>잠재 요인 기반의 행렬 분해 이해</h2>

그래서 4 X 5의 원본행렬이고 factor가 2개인걸로 계싼이 된다면(factor는 사용자가 정할 수 있다. 이 숫자를 늘리면(5라던가. 여기서.) 오버피팅이 될 수 있기 때문에 그렇게 하지 않는다.)

4x2(Mxk) 2x4(KxN)

<img src="./img/LatentFactorCom2.png">

<h2>행렬 분해를 통한 평점 예측</h2>

앞에 내용을 이반화시켜서 해보자.

r(2,4) ((2는 위치 인덱스 아니라 편의상 쓰는 숫자이다)) 는 3이 나오는데

P2와 Q transpose 4 의 값을 계산하는거다.

내적을하면 r의 예측값이 나오고

<img src="./img/MatrixRecord1.png">



r(2,3)은  p2의 user2의 값에 item 3의 qt3의 값을 내적해서 계산하는거다.

<img src="./img/MatrixRecord2.png">

<h2>행렬 분해를 통한 평점 예측</h2>

즉 그냥 내적을 곱하면 된다. 그러면 예측 평점 값이 나온다.

P 내적 Q.T 는 R이 나온다.

<img src="./img/MatrixRecord3.png">

<h2>사용자-아이템 평점 행렬 분해 이슈</h2>

그런데 이슈가 좀 있다. P와 Q를 모르는데 어떻게 R을 예측할 수 있나?

일반적으로 SVD는 Missing Value가 없는 행렬에 적용 가능하다. 

그럼 SVD를 쓰기는 쓰는데 어떻게 예측하나? 경사 하강법으로 구현한다.(이게 기억이 안나면 5장으로 다시 가보기)

비용이 가장 최소가 되는 비용함수를 구한다(편미분을 해서) 계속 루프를 돌면서 이터레이션하면서 업데이트를 한다.

더 이상 비용이 작아지 않는. 그때가 최적화

<img src="./img/UserItemIssue.png">

<h2>경사 하강법 기반의 행렬 분해</h2>

행렬 분해 방법은 경사 하강법과 유사하다. 원본이 M x N이면 P와 Q를 0으로 채운다. 

그 다음에  P와 Q.T를 곱해 예측 값을 계산하고 오류 값을 서로 비교한다. 오류 값이 작아지는 방향성으로 업데이트를 한다.

그래서 무조건 업데이트하면 안된다. 편미분 값을 구해서 미분에 기반한 값으로 업데이트를 해야한다.

만족할 만한 값을 가질 때까지 2와 3을 반복하면서 업데이트를 해 나간다.

<img src="./img/GradientMatrix.png">

<h2>경사 하강법 기반의 행렬 분해 비용 함수</h2>

비용함수 식을 보면 r(u,i)가 실제 값이고 PuQi.T 이게 예측 값이다. 비용함수는 어떻게 되나?

오류 최소화만 생각하면 과적합이 되므로 L2 규제를 적용하게 된다.

<img src="./img/GradientMatrixFunc.png">

<h2>경사 하강법 기반의 행렬 분해 업데이트 식</h2>

식의 도출은 길어서 여기서 설명 안함. 이런식으로 도출이 된다고만 이해하면 충분하다.

새롭게 업데이트 되는 Pu + 뮤

e(u,i)는 실제값 - 예측 값

람다: L2 Regularization 계수

<img src="./img/GradientMatrixFomul.png">

위 식 두개를 구현해볼거임. 

### 경사하강을 이용한 행렬 분해

**원본 행렬 R 및 R을 분해할 P와 Q를 임의의 정규분포를 가진 랜덤값으로 초기화**

먼저 경사하강법이 어떻게 진행되는지 간단하게 보자

In [1]:
import numpy as np

# 원본 행렬 R 생성, 분해 행렬 P와 Q 초기화, 잠재요인 차원 K는 3 설정. 
# R은 4 x 5 . Null 값이 있는데 이걸 예측하는거임
# P는 4 x 3 이 될거고 Q.T는 3 x 5가 될 것임 Q는 5 x 3 이 될 것임
R = np.array([[4, np.NaN, np.NaN, 2, np.NaN ],
              [np.NaN, 5, np.NaN, 3, 1 ],
              [np.NaN, np.NaN, 3, 4, 4 ],
              [5, 2, 1, 2, np.NaN ]])

num_users, num_items = R.shape
K=3

# P와 Q 매트릭스의 크기를 지정하고 정규분포를 가진 random한 값으로 입력합니다. 
# Q를 0 값으로 넣지 않고 정규분포 값으로 초기화해서 넣을거임. 그러면 경사하강을 할때 좀더 빠르게 근사치에 가까워진다.
# 그것을 수행하기 위해 넘파이에 random 밑에 normal함수를 호출하면 사이즈를 쉐이프 형태로 지정해주면 쉐이프형태를 가지는 Ndarray를 정규분포 값으로 채워준다.
np.random.seed(1)
P = np.random.normal(scale=1./K, size=(num_users, K))
Q = np.random.normal(scale=1./K, size=(num_items, K))
print("P:",P)
print("Q:",Q)

P: [[ 0.54144845 -0.2039188  -0.17605725]
 [-0.35765621  0.28846921 -0.76717957]
 [ 0.58160392 -0.25373563  0.10634637]
 [-0.08312346  0.48736931 -0.68671357]]
Q: [[-0.1074724  -0.12801812  0.37792315]
 [-0.36663042 -0.05747607 -0.29261947]
 [ 0.01407125  0.19427174 -0.36687306]
 [ 0.38157457  0.30053024  0.16749811]
 [ 0.30028532 -0.22790929 -0.04096341]]


**비용계산 함수를 생성. 분해된 행렬 P와 Q.T를 내적하여 예측 행렬 생성하고**

**실제 행렬에서 널이 아닌 값의 위치에 있는 값만 예측 행렬의 값과 비교하여 RMSE값을 계산하고 반환**

In [2]:
from sklearn.metrics import mean_squared_error

# get_rmse는 실제 행렬과 예측 행렬의 값의 차이를 계산하는 함수이다.
def get_rmse(R, P, Q, non_zeros):
    error = 0
    # 두개의 분해된 행렬 P와 Q.T의 내적으로 예측 R 행렬 생성
    full_pred_matrix = np.dot(P, Q.T)
    
    # 실제 R 행렬에서 널이 아닌 값의 위치 인덱스 추출하여 실제 R 행렬과 예측 행렬의 RMSE 추출. x 는 행 인덱스 y는 열 인덱스
    x_non_zero_ind = [non_zero[0] for non_zero in non_zeros]
    y_non_zero_ind = [non_zero[1] for non_zero in non_zeros]
    R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]
    full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind]
      
    mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
    rmse = np.sqrt(mse)
    
    return rmse


**경사하강법에 기반하여 P와 Q의 원소들을 업데이트 수행**
![](./sgd.png)

여기서 get_rmse를 호출한다. 여기서 행렬 분해를 하는 것임.

In [3]:
# R > 0 인 행 위치, 열 위치, 값을 non_zeros 리스트에 저장. 리스트 컴프리헨션을 중복으로 수행한 코드.
non_zeros = [ (i, j, R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j] > 0 ]

steps=1000
learning_rate=0.01
r_lambda=0.01

# SGD 기법으로 P와 Q 매트릭스를 계속 업데이트. 
for step in range(steps):
    for i, j, r in non_zeros:
        # 실제 값과 예측 값의 차이인 오류 값 구함
        eij = r - np.dot(P[i, :], Q[j, :].T)
        # Regularization을 반영한 SGD 업데이트 공식 적용
        P[i,:] = P[i,:] + learning_rate*(eij * Q[j, :] - r_lambda*P[i,:])
        Q[j,:] = Q[j,:] + learning_rate*(eij * P[i, :] - r_lambda*Q[j,:])
        
    # 원본행렬 R 값과 경사하강법에서 계산된 P와 Q 값. 그리고 non_zeros는 뭘 뜻하냐면 원본 행렬에서 null 
    rmse = get_rmse(R, P, Q, non_zeros)
    if (step % 50) == 0 :
        print("### iteration step : ", step," rmse : ", rmse)



### iteration step :  0  rmse :  3.2388050277987723
### iteration step :  50  rmse :  0.4876723101369648
### iteration step :  100  rmse :  0.1564340384819247
### iteration step :  150  rmse :  0.07455141311978046
### iteration step :  200  rmse :  0.04325226798579314
### iteration step :  250  rmse :  0.029248328780878973
### iteration step :  300  rmse :  0.022621116143829466
### iteration step :  350  rmse :  0.019493636196525135
### iteration step :  400  rmse :  0.018022719092132704
### iteration step :  450  rmse :  0.01731968595344266
### iteration step :  500  rmse :  0.016973657887570753
### iteration step :  550  rmse :  0.016796804595895633
### iteration step :  600  rmse :  0.01670132290188466
### iteration step :  650  rmse :  0.01664473691247669
### iteration step :  700  rmse :  0.016605910068210026
### iteration step :  750  rmse :  0.016574200475705
### iteration step :  800  rmse :  0.01654431582921597
### iteration step :  850  rmse :  0.01651375177473524
### iterati

P와 Q가 업데이트 됐으니까 다시 결합을 해보자

In [4]:
pred_matrix = np.dot(P, Q.T)
print('예측 행렬:\n', np.round(pred_matrix, 3))

예측 행렬:
 [[3.991 0.897 1.306 2.002 1.663]
 [6.696 4.978 0.979 2.981 1.003]
 [6.677 0.391 2.987 3.977 3.986]
 [4.968 2.005 1.006 2.017 1.14 ]]


In [ ]:
R = np.array([[4, np.NaN, np.NaN, 2, np.NaN ],
              [np.NaN, 5, np.NaN, 3, 1 ],
              [np.NaN, np.NaN, 3, 4, 4 ],
              [5, 2, 1, 2, np.NaN ]])

### 행렬 분해 기반의 잠재 요인 협업 필터링 실습

**경사하강법 기반의 행렬 분해 함수 생성**

In [5]:
# 원본 행렬이 들어올 것 임.(무비렌즈 데이터에서 10만개 레이팅 받았던 그 데이터들을 사용자 아이템 평점 행렬로 변환한 다음에) 그 원본행렬에 대해서 K (latentFactor)
def matrix_factorization(R, K, steps=200, learning_rate=0.01, r_lambda = 0.01):
    num_users, num_items = R.shape
    # P와 Q 매트릭스의 크기를 지정하고 정규분포를 가진 랜덤한 값으로 입력합니다. 
    np.random.seed(1)
    P = np.random.normal(scale=1./K, size=(num_users, K))
    Q = np.random.normal(scale=1./K, size=(num_items, K))

    break_count = 0
       
    # R > 0 인 행 위치, 열 위치, 값을 non_zeros 리스트 객체에 저장. 
    non_zeros = [ (i, j, R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j] > 0 ]
   
    # SGD기법으로 P와 Q 매트릭스를 계속 업데이트. 
    for step in range(steps):
        for i, j, r in non_zeros:
            # 실제 값과 예측 값의 차이인 오류 값 구함
            eij = r - np.dot(P[i, :], Q[j, :].T)
            # Regularization을 반영한 SGD 업데이트 공식 적용
            P[i,:] = P[i,:] + learning_rate*(eij * Q[j, :] - r_lambda*P[i,:])
            Q[j,:] = Q[j,:] + learning_rate*(eij * P[i, :] - r_lambda*Q[j,:])
       
        rmse = get_rmse(R, P, Q, non_zeros)
        if (step % 10) == 0 :
            print("### iteration step : ", step," rmse : ", rmse)
            
    return P, Q

In [6]:
import pandas as pd
import numpy as np

movies = pd.read_csv('./ml-latest-small/movies.csv')
ratings = pd.read_csv('./ml-latest-small/ratings.csv')
ratings = ratings[['userId', 'movieId', 'rating']]
ratings_matrix = ratings.pivot_table('rating', index='userId', columns='movieId')

# title 컬럼을 얻기 위해 movies 와 조인 수행
rating_movies = pd.merge(ratings, movies, on='movieId')

# columns='title' 로 title 컬럼으로 pivot 수행. 
ratings_matrix = rating_movies.pivot_table('rating', index='userId', columns='title')

In [7]:
P, Q = matrix_factorization(ratings_matrix.values, K=50, steps=200, learning_rate=0.01, r_lambda = 0.01)
pred_matrix = np.dot(P, Q.T)

### iteration step :  0  rmse :  2.9023619751336867
### iteration step :  10  rmse :  0.7335768591017927
### iteration step :  20  rmse :  0.5115539026853442
### iteration step :  30  rmse :  0.37261628282537446
### iteration step :  40  rmse :  0.2960818299181014
### iteration step :  50  rmse :  0.2520353192341642
### iteration step :  60  rmse :  0.22487503275269854
### iteration step :  70  rmse :  0.20685455302331537
### iteration step :  80  rmse :  0.19413418783028685
### iteration step :  90  rmse :  0.18470082002720403
### iteration step :  100  rmse :  0.17742927527209104
### iteration step :  110  rmse :  0.17165226964707486
### iteration step :  120  rmse :  0.1669518194687172
### iteration step :  130  rmse :  0.16305292191997542
### iteration step :  140  rmse :  0.15976691929679643
### iteration step :  150  rmse :  0.1569598699945732
### iteration step :  160  rmse :  0.15453398186715428
### iteration step :  170  rmse :  0.15241618551077643
### iteration step :  180  r

예측된 행렬을 데이터프레임으로 만들어보자

In [8]:
ratings_pred_matrix = pd.DataFrame(data=pred_matrix, index= ratings_matrix.index,
                                   columns = ratings_matrix.columns)

ratings_pred_matrix.head(3)

title   '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
userId                                                        
1         3.055084                                 4.092018   
2         3.170119                                 3.657992   
3         2.307073                                 1.658853   

title   'Round Midnight (1986)  'Salem's Lot (2004)  \
userId                                                
1                     3.564130             4.502167   
2                     3.308707             4.166521   
3                     1.443538             2.208859   

title   'Til There Was You (1997)  'Tis the Season for Love (2015)  \
userId                                                               
1                        3.981215                         1.271694   
2                        4.311890                         1.275469   
3                        2.229486                         0.780760   

title   'burbs, The (1989)  'night Mother (1986)  (500) Days of Summer (2009)  \
userId                                                                          
1                 3.603274              2.333266                     5.091749   
2                 4.237972              1.900366                     3.392859   
3                 1.997043              0.924908                     2.970700   

title   *batteries not included (1987)  ...  Zulu (2013)  [REC] (2007)  \
userId                                  ...                              
1                             3.972454  ...     1.402608      4.208382   
2                             3.647421  ...     0.973811      3.528264   
3                             2.551446  ...     0.520354      1.709494   

title   [REC]² (2009)  [REC]³ 3 Génesis (2012)  \
userId                                           
1            3.705957                 2.720514   
2            3.361532                 2.672535   
3            2.281596                 1.782833   

title   anohana: The Flower We Saw That Day - The Movie (2013)  \
userId                                                           
1                                                2.787331        
2                                                2.404456        
3                                                1.635173        

title   eXistenZ (1999)  xXx (2002)  xXx: State of the Union (2005)  \
userId                                                                
1              3.475076    3.253458                        2.161087   
2              4.232789    2.911602                        1.634576   
3              1.323276    2.887580                        1.042618   

title   ¡Three Amigos! (1986)  À nous la liberté (Freedom for Us) (1931)  
userId                                                                    
1                    4.010495                                   0.859474  
2                    4.135735                                   0.725684  
3                    2.293890                                   0.396941  

[3 rows x 9719 columns]

In [9]:
def get_unseen_movies(ratings_matrix, userId):
    # userId로 입력받은 사용자의 모든 영화정보 추출하여 Series로 반환함. 
    # 반환된 user_rating 은 영화명(title)을 index로 가지는 Series 객체임. 
    user_rating = ratings_matrix.loc[userId,:]
    
    # user_rating이 0보다 크면 기존에 관람한 영화임. 대상 index를 추출하여 list 객체로 만듬
    already_seen = user_rating[ user_rating > 0].index.tolist()
    
    # 모든 영화명을 list 객체로 만듬. 
    movies_list = ratings_matrix.columns.tolist()
    
    # list comprehension으로 already_seen에 해당하는 movie는 movies_list에서 제외함. 
    unseen_list = [ movie for movie in movies_list if movie not in already_seen]
    
    return unseen_list

In [10]:
def recomm_movie_by_userid(pred_df, userId, unseen_list, top_n=10):
    # 예측 평점 DataFrame에서 사용자id index와 unseen_list로 들어온 영화명 컬럼을 추출하여
    # 가장 예측 평점이 높은 순으로 정렬함. 
    recomm_movies = pred_df.loc[userId, unseen_list].sort_values(ascending=False)[:top_n]
    return recomm_movies

In [11]:
# 사용자가 관람하지 않는 영화명 추출   
unseen_list = get_unseen_movies(ratings_matrix, 9)

# 잠재요인 기반 협업 필터링으로 영화 추천 
recomm_movies = recomm_movie_by_userid(ratings_pred_matrix, 9, unseen_list, top_n=10)

# 평점 데이타를 DataFrame으로 생성. 
recomm_movies = pd.DataFrame(data=recomm_movies.values,index=recomm_movies.index,columns=['pred_score'])
recomm_movies

pred_score
title                                                         
Rear Window (1954)                                    5.704612
South Park: Bigger, Longer and Uncut (1999)           5.451100
Rounders (1998)                                       5.298393
Blade Runner (1982)                                   5.244951
Roger & Me (1989)                                     5.191962
Gattaca (1997)                                        5.183179
Ben-Hur (1959)                                        5.130463
Rosencrantz and Guildenstern Are Dead (1990)          5.087375
Big Lebowski, The (1998)                              5.038690
Star Wars: Episode V - The Empire Strikes Back ...    4.989601